version: "3"

services:
  bojack-app:
    build:
      context: .
      dockerfile: deployments/Dockerfile.app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./deployments/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - bojack-db
    networks:
      - bojack_network
  bojack-db:
    build:
      context: .
      dockerfile: deployments/Dockerfile.db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bojack_db
      MYSQL_USER: bojack_user
      MYSQL_PASSWORD: P@ssw0rd
    ports:
      - "3307:3306"
    networks:
      - bojack_network
networks:
  bojack_network:
    driver: bridge
